export type Unit = { id: number; code: string; name_ru: string; allows_fraction: number };
export type Category = { id: number; code: string; default_name: string; parent_id: number | null };
export type Product = {
  id: number;
  category_id: number;
  unit_id: number;
  sku: string;
  default_name: string;
  default_name_original?: string;
  default_name_source_lang?: string | null;
  tracking_type: 'quantity' | 'serial' | 'batch';
  current_purchase_price: string;
  current_sale_price: string;
  reorder_threshold: string;
  category_name: string;
  category_name_original?: string;
  category_name_source_lang?: string | null;
  category_code?: string;
  show_in_sales?: number;
  show_in_repair?: number;
  show_in_projects?: number;
  show_in_creative?: number;
  unit_name_ru: string;
  primary_barcode?: string | null;
  quantity_on_hand?: string;
  quantity_reserved?: string;
  quantity_available?: string;
};
export type Service = {
  id: number;
  code: string;
  default_name: string;
  default_name_original?: string;
  default_name_source_lang?: string | null;
  module: string;
  default_price: string;
  category_name: string;
  category_name_original?: string;
};
export type Supplier = {
  id: number;
  name: string;
  name_original?: string;
  name_source_lang?: string | null;
  phone?: string | null;
  email?: string | null;
  address_text?: string | null;
  notes?: string | null;
  is_active?: number;
};
export type ProductSupplierLink = {
  supplier_id: number;
  supplier_name: string;
  supplier_phone: string | null;
  supplier_email: string | null;
  supplier_sku: string | null;
  last_purchase_price: string | null;
};
export type ProductRequest = {
  categoryId: number;
  unitId: number;
  sku: string;
  defaultName: string;
  trackingType: 'quantity' | 'serial' | 'batch';
  currentPurchasePrice: number;
  currentSalePrice: number;
  reorderThreshold: number;
  barcode?: string | null;
};
export type ProductUpdateRequest = Partial<Omit<ProductRequest, 'barcode'>>;
export type CategoryRequest = {
  code: string;
  defaultName: string;
  parentId?: number | null;
  showInSales: boolean;
  showInRepair: boolean;
  showInProjects: boolean;
  showInCreative: boolean;
};
export type SupplierRequest = { name: string; phone?: string | null; email?: string | null; addressText?: string | null; notes?: string | null };
export type ProductSupplierRequest = {
  supplierId: number;
  supplierSku?: string | null;
  lastPurchasePrice?: number | null;
};
