CREATE TABLE finance_provider_catalog (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  provider_type VARCHAR(32) NOT NULL,
  name VARCHAR(255) NOT NULL,
  short_name VARCHAR(120) NULL,
  parent_code VARCHAR(64) NULL,
  country_code VARCHAR(8) NOT NULL DEFAULT 'EG',
  logo_url LONGTEXT NULL,
  source_url VARCHAR(500) NULL,
  notes TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_finance_provider_catalog_code (code),
  KEY idx_finance_provider_catalog_type (provider_type),
  KEY idx_finance_provider_catalog_parent (parent_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE finance_payment_accounts
  ADD COLUMN provider_code VARCHAR(64) NULL AFTER provider,
  ADD KEY idx_finance_payment_accounts_provider_code (provider_code);

ALTER TABLE finance_payment_methods
  ADD COLUMN provider_code VARCHAR(64) NULL AFTER provider,
  ADD KEY idx_finance_payment_methods_provider_code (provider_code);

INSERT INTO finance_provider_catalog (code, provider_type, name, short_name, parent_code, source_url, sort_order)
VALUES
  ('BANK_NBE', 'bank', 'البنك الأهلي المصري', 'NBE', NULL, 'https://www.bankygate.com/banky/banks', 10),
  ('BANK_CIB', 'bank', 'البنك التجاري الدولي', 'CIB', NULL, 'https://www.bankygate.com/banky/banks', 20),
  ('BANK_BM', 'bank', 'بنك مصر', 'BM', NULL, 'https://www.bankygate.com/banky/banks', 30),
  ('BANK_QNB', 'bank', 'بنك QNB مصر', 'QNB', NULL, 'https://www.bankygate.com/banky/banks', 40),
  ('BANK_HSBC', 'bank', 'HSBC مصر', 'HSBC', NULL, 'https://www.bankygate.com/banky/banks', 50),
  ('BANK_NEXT', 'bank', 'بنك نكست', 'bank nxt', NULL, 'https://www.bankygate.com/banky/banks', 60),
  ('BANK_ATTIJARIWAFA', 'bank', 'التجاري وفا بنك', 'Attijariwafa', NULL, 'https://www.bankygate.com/banky/banks', 70),
  ('BANK_BLOM', 'bank', 'بنك بلوم مصر', 'BLOM', NULL, 'https://www.bankygate.com/banky/banks', 80),
  ('BANK_CA', 'bank', 'كريدي أجريكول مصر', 'CA Egypt', NULL, 'https://www.bankygate.com/banky/banks', 90),
  ('BANK_AIB', 'bank', 'المصرف العربي الدولي', 'AIB', NULL, 'https://www.bankygate.com/banky/banks', 100),
  ('BANK_ADIB', 'bank', 'مصرف أبوظبي الإسلامي', 'ADIB', NULL, 'https://www.bankygate.com/banky/banks', 110),
  ('BANK_ABE', 'bank', 'البنك الزراعي المصري', 'ABE', NULL, 'https://www.bankygate.com/banky/banks', 120),
  ('BANK_STANDARD', 'bank', 'ستاندرد تشارترد', 'Standard Chartered', NULL, 'https://www.bankygate.com/banky/banks', 130),
  ('BANK_ALEX', 'bank', 'بنك الإسكندرية', 'Alex Bank', NULL, 'https://www.bankygate.com/banky/banks', 140),
  ('BANK_HDB', 'bank', 'بنك التعمير والإسكان', 'HDB', NULL, 'https://www.bankygate.com/banky/banks', 150),
  ('BANK_NBK', 'bank', 'بنك الكويت الوطني - مصر', 'NBK', NULL, 'https://www.bankygate.com/banky/banks', 160),
  ('BANK_ABC', 'bank', 'بنك ABC', 'ABC', NULL, 'https://www.bankygate.com/banky/banks', 170),
  ('BANK_SCB', 'bank', 'بنك قناة السويس', 'SCB', NULL, 'https://www.bankygate.com/banky/banks', 180),
  ('BANK_EGBANK', 'bank', 'EGBANK', 'EGBANK', NULL, 'https://www.bankygate.com/banky/banks', 190),
  ('BANK_FAB', 'bank', 'بنك أبوظبي الأول - مصر', 'FAB', NULL, 'https://www.bankygate.com/banky/banks', 200),
  ('BANK_UB', 'bank', 'المصرف المتحد', 'UB', NULL, 'https://www.bankygate.com/banky/banks', 210),
  ('BANK_MID', 'bank', 'ميد بنك', 'MID', NULL, 'https://www.bankygate.com/banky/banks', 220),
  ('BANK_IDB', 'bank', 'بنك التنمية الصناعية', 'IDB', NULL, 'https://www.bankygate.com/banky/banks', 230),
  ('BANK_EMIRATES_NBD', 'bank', 'بنك الإمارات دبي الوطني', 'Emirates NBD', NULL, 'https://www.bankygate.com/banky/banks', 240),
  ('BANK_EBANK', 'bank', 'بنك تنمية الصادرات', 'EBANK', NULL, 'https://www.bankygate.com/banky/banks', 250),
  ('BANK_SAIB', 'bank', 'saib bank', 'SAIB', NULL, 'https://www.bankygate.com/banky/banks', 260),
  ('BANK_ARAB', 'bank', 'البنك العربي', 'Arab Bank', NULL, 'https://www.bankygate.com/banky/banks', 270),
  ('BANK_FAISAL', 'bank', 'بنك فيصل الإسلامي', 'Faisal', NULL, 'https://www.bankygate.com/banky/banks', 280),
  ('BANK_CAIRO', 'bank', 'بنك القاهرة', 'BDC', NULL, 'https://www.bankygate.com/banky/banks', 290),
  ('BANK_AAIB', 'bank', 'البنك العربي الأفريقي الدولي', 'AAIB', NULL, 'https://www.bankygate.com/banky/banks', 300),
  ('WALLET_NBE_PHONE_CASH', 'wallet', 'الأهلي فون كاش', 'Phone Cash', 'BANK_NBE', 'https://www.bankygate.com/Banky/Products/E-Wallets', 1000),
  ('WALLET_CIB_SMART', 'wallet', 'Smart Wallet', 'Smart Wallet', 'BANK_CIB', 'https://www.bankygate.com/Banky/Products/E-Wallets', 1010),
  ('WALLET_BM', 'wallet', 'BM Wallet', 'BM Wallet', 'BANK_BM', 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1020),
  ('WALLET_QNB', 'wallet', 'محفظة QNB الأهلي الإلكترونية', 'QNB Wallet', 'BANK_QNB', 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1030),
  ('WALLET_CAIRO_CASH', 'wallet', 'محفظة قاهرة كاش', 'Cairo Cash', 'BANK_CAIRO', 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1040),
  ('WALLET_AIB', 'wallet', 'AIB Wallet', 'AIB Wallet', 'BANK_AIB', 'https://www.bankygate.com/Banky/Products/E-Wallets', 1050),
  ('WALLET_AGRI', 'wallet', 'Agri Wallet', 'Agri Wallet', 'BANK_ABE', 'https://www.bankygate.com/Banky/Products/E-Wallets', 1060),
  ('WALLET_CASH2GO', 'wallet', 'Cash2Go', 'Cash2Go', 'BANK_FAB', 'https://www.bankygate.com/Banky/Products/E-Wallets', 1070),
  ('WALLET_ABK', 'wallet', 'ABK Wallet', 'ABK Wallet', NULL, 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1080),
  ('WALLET_BLOM', 'wallet', 'BLOM Wallet', 'BLOM Wallet', 'BANK_BLOM', 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1090),
  ('WALLET_UB', 'wallet', 'محفظة UB الرقمية', 'UB Wallet', 'BANK_UB', 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1100),
  ('WALLET_FAISAL', 'wallet', 'فيصل كاش', 'Faisal Cash', 'BANK_FAISAL', 'https://www.bankygate.com/Banky/Products/E-Wallets?page=2&query=', 1110),
  ('MACHINE_FAWRY', 'payment_machine', 'فوري', 'Fawry', NULL, NULL, 2000),
  ('MACHINE_AMAN', 'payment_machine', 'أمان', 'Aman', NULL, NULL, 2010),
  ('MACHINE_MASARY', 'payment_machine', 'مصاري', 'Masary', NULL, NULL, 2020),
  ('MACHINE_BEE', 'payment_machine', 'بي', 'Bee', NULL, NULL, 2030),
  ('MACHINE_CASH_MASR', 'payment_machine', 'كاش مصر', 'Cash Masr', NULL, NULL, 2040),
  ('MACHINE_KHALES', 'payment_machine', 'خالص', 'Khales', NULL, NULL, 2050),
  ('CASH_SAFE', 'cash_holder', 'خزنة المحل', 'Store Safe', NULL, NULL, 3000),
  ('CASH_DRAWER_MAIN', 'cash_holder', 'درج الكاشير الرئيسي', 'Main Drawer', NULL, NULL, 3010)
ON DUPLICATE KEY UPDATE
  provider_type = VALUES(provider_type),
  name = VALUES(name),
  short_name = VALUES(short_name),
  parent_code = VALUES(parent_code),
  source_url = VALUES(source_url),
  sort_order = VALUES(sort_order),
  is_active = TRUE;
